const ROBOT_APP_TYPES = {
  APP_TYPE_DISABLED : 'DISABLED',
  APP_TYPE_REDIRECT : 'REDIRECT',
  APP_TYPE_AUTO : 'AUTO',
  APP_TYPE_TERMINAL : 'TERMINAL',
  APP_TYPE_SCALE : 'SCALE',
  APP_TYPE_SCANNER : 'SCANNER',
  APP_TYPE_BINTIP : 'BINTIP',
  APP_TYPE_FORKLIFT : 'FORKLIFT',
  APP_TYPE_DUALSCAN : 'DUALSCAN',
  APP_TYPE_LABELPRINT : 'LABELPRINT',
};

module.exports = ROBOT_APP_TYPES;