const FORKLIFT_STATES = {
  LOAD_SCAN_PALLET : "LOAD-SCAN-PALLET",
  LOAD_SCAN_LOCATION : "LOAD-SCAN-LOC",
  TRANSIT : "TRANSIT",
  UNLOAD_SCANNED_PALLET : "UNLOAD-SCAN-PALLET",
  UNLOAD_SCANNED_LOCATION : "UNLOAD-SCAN-LOC"
};

module.exports = FORKLIFT_STATES;